### ISSUE TITLE
Do not show the branch switcher on the page edit children tab

### ISSUE THREAD

**Issue by ivangretsky** [teppokoivula/AdminRestrictBranchSelect#1]
Good day!

I just found that the changes that ARBS adds to the Page List also apply to the children tab on the page edit screen. I see this is an unintended side effect that looks like a bug. @teppokoivula , could we change that so the select only appears where it should by the logic?

**Comment by teppokoivula** [comment]
Thanks, Ivan. This should be fixed now.

There was some code intended to prevent this, so not sure if it just never worked, or if somethings changed in the markup — anyway, hopefully this'll get it sorted out :)
